# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [31]:
array = np.random.randint(0, 1000, (10, 10))
print(array)
print("Мин: ", array.min())
print("Макс: ", array.max())

[[356 272 760 405 756 894 522 841 906 875]
 [957 456 580 800 953 855 728  19 126 859]
 [975 862 820 731 618 389 298 624 836 653]
 [746  17 291 660 104 849 361 643 689 827]
 [829 351 401 535  55 389 866  18 853 781]
 [279 454 587  27  38 487 955  23 461 316]
 [614 894  37 900 691 345 103 879 129 785]
 [  9 835 636 612 407 630 923 126 732 404]
 [115 156 342 470 699 204 758 683 843 140]
 [ 70 404 881 676 377 348 525 282 792 112]]
Мин:  9
Макс:  975


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [32]:
matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1  # Нечетные строки, четные столбцы
matrix[::2, 1::2] = 1  # Четные строки, нечетные столбцы

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [33]:
z = np.arange(11)
z[(z >= 3) & (z <= 8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [44]:
z = np.random.rand(5, 10)
z = z - z.mean(axis=1,keepdims=True)
print(z)


[[-0.26516911 -0.36012317 -0.03743627  0.41670688 -0.04801913 -0.31695806
   0.05232227  0.57325283  0.32005869 -0.33463494]
 [ 0.23163716 -0.25018314  0.36418767  0.19554453 -0.57338362 -0.06966663
   0.17781168  0.10530136  0.31413639 -0.4953854 ]
 [ 0.06095838 -0.36483722 -0.41418892  0.22600217  0.17738629  0.10762331
   0.10652616 -0.17064079  0.33015538 -0.05898477]
 [-0.31407688  0.32869569  0.23784561 -0.25031649 -0.08184215 -0.19111941
  -0.13931873  0.20843913  0.09015775  0.11153547]
 [ 0.09769796 -0.17101089  0.06060425  0.0472536  -0.17523124  0.24908718
  -0.43933416  0.15974223  0.09672235  0.0744687 ]]


5. Поменяйте 1 и 2 строки матрицы

In [45]:
z = np.arange(25).reshape(5,5)
z[[0, 1]] = z[[1, 0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [47]:
z = np.random.random((10,2))
r = np.hypot(z[:, 0], z[:, 1]) # радиус
theta = np.arctan2(z[:, 1], z[:, 0]) # угол
polar = np.column_stack((r, theta))
print(polar)

[[1.0067838  0.63032309]
 [0.93667954 0.75142709]
 [1.02509112 1.09001965]
 [0.94482185 0.55001762]
 [0.77427917 0.16827382]
 [0.54620889 0.41463653]
 [0.87887926 1.09168971]
 [0.88295576 0.60688413]
 [0.91402775 1.49660595]
 [1.04828804 0.33026672]]


7. Заменить максимальный элемент массива на ноль

In [54]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.06378627 0.62877566 0.74518755 0.38608848 0.29530536 0.
 0.57890473 0.36137524 0.28294849 0.62637552]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [110]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(np.unique(i))
z[np.unique(i)]+=1
print(z)

[0 2 3 4 5 7 8 9]
[2. 1. 2. 2. 2. 2. 1. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [105]:
z = np.array([1,2,3,4,5])
result = np.zeros(len(z) + (len(z)-1) * 3)
result[::(4)] = z
print(result)

[1 2 3 4 5] [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [103]:
z = np.arange(100)
v = np.random.uniform(0,100)
result = z[np.argmin(np.abs(z - v))]
print(v,result)

91.02425618262772 91


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])  # int64
np.array([1., 4, 2, 5, 3])  # float64
np.array([1, 4, 2, 5, 3], dtype='float128')  # float128
np.array([1., 4, 2, 5, 3], dtype='complex128')  # complex128
np.array([1, 4, 2, 5, 3], dtype ='float64')  # float64
np.array([1, 4, 2, 5, 3], dtype =int64)  # int64
np.array([1, 4, 2, 5, 3], dtype='bool')  # bool
np.array([1, 4, 2, 5, 3], dtype='str')  # <U1
np.array([1, 4, 2, 5, '3'])  # <U21
np.array([1, -4, 2, 0, 1j])  # complex128
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

Ответ:

1. `'41'` - строка `'4'` + строка `'1'`
2. `-4` - `False or -4` = `-4` (первый False, второй truthy)
3. `False` - `False and -4` = `False` (and возвращает первый False)
4. `1` - `True` преобразовалось в `1` при dtype='int64'
5. `TypeError` - нельзя преобразовать комплексное число `1j` в int
6. `'1j'` - комплексное число как строка, взяли последний элемент
7. `'333'` - массив стал строковым, `'3' * 3` = `'333'`

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```

Ответ:

1. Матрица 3х5 из единиц типа float

2. Матрица 3х5 заполненная значением 3.14

3. Одномерный массив из 5 равноотстоящих значений от 0 до 1: [0.0, 0.25, 0.5, 0.75, 1.0]

4. Диагональная матрица 3х3 с элементами 1, 3, 5 на диагонали

5. Ошибка: функция np.smile() не существует

6. Матрица 3х3 со случайными значениями от 0 до 1

7. Единичная матрица 3х3

8. Одномерный массив из 3 неинициализированных значений


In [130]:
print(np.ones((3, 5), dtype=float))
print(np.full((3, 5), 3.14))
print(np.linspace(0, 1, 5))
print(np.diag((1, 3, 5)))
# print(np.smile((1, 3, 5)))
print(np.random.random((3, 3)))
print(np.eye(3))
print(np.empty(3))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[0.   0.25 0.5  0.75 1.  ]
[[1 0 0]
 [0 3 0]
 [0 0 5]]
[[0.04281768 0.98791016 0.82361331]
 [0.7168757  0.86804277 0.92744415]
 [0.28006782 0.43135338 0.13165797]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

Ответ
``` python
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
```

In [137]:
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]

print(X)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```

Ответ:

1. `np.split(grid, [2])` делит массив по строкам `axis=0`, создавая 2 части: первые 2 строки и остальные

2. `np.split(grid, [2], axis=1)` делит массив по столбцам `axis=1`, создавая 2 части: первые 2 столбца и остальные

**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

Ответ:

1. `[1, 2, 3] + [3, 2, 1]` конкатенация списков, результат: `[1, 2, 3, 3, 2, 1]`

2. `np.array([1, 2, 3]) + np.array([3, 2, 1])` — поэлементное сложение массивов, результат: `array([4, 4, 4])`

**7**. Как в CodeLab измерить время выполнения кода?

Ответ:

`%time` или `%timeit` перед строкой

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

Овтет:

Ошибочка, М не определена))

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

Ответ:

`array([1, 2, 4])`

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Ответ:

Преимущество:

- Операции выполняются быстрее благодаря реализации на C и векторизации.
- Более эффективное использование памяти (элементы одного типа, хранятся компактно).
- Встроенные функции для математических операций, линейной алгебры, статистики и т.д.

Обусловлено:
- Использованием однотипных данных (например, только float64), что упрощает хранение и обработку.
- Непрерывным размещением данных в памяти.
- Оптимизированными низкоуровневыми операциями.